import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { Order } from '../../orders/entities/order.entity';
import { Service } from '../../services/entities/service.entity';
import { User } from '../../users/entities/user.entity';
import { RecommendationPriority } from './recommendation-priority.enum';
import { RecommendationStatus } from './recommendation-status.enum';

@Entity()
export class Recommendation {
  @ApiProperty({
    example: '550e8400-e29b-41d4-a716-446655440000',
    description: 'Recommendation ID',
  })
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ApiProperty({
    example: '550e8400-e29b-41d4-a716-446655440000',
    description: 'Client user ID',
  })
  @Column({ type: 'uuid' })
  userId: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'userId' })
  user: User;

  @ApiProperty({
    example: '550e8400-e29b-41d4-a716-446655440000',
    description: 'Recommended service ID',
  })
  @Column({ type: 'uuid' })
  serviceId: string;

  @ManyToOne(() => Service, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'serviceId' })
  service: Service;

  @ApiPropertyOptional({
    example: '550e8400-e29b-41d4-a716-446655440000',
    description: 'Related order ID when recommendation is purchased',
  })
  @Column({ type: 'uuid', nullable: true })
  orderId: string | null;

  @ManyToOne(() => Order, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'orderId' })
  order: Order | null;

  @ApiProperty({
    enum: RecommendationStatus,
    description: 'Recommendation lifecycle status',
    default: RecommendationStatus.Recommended,
  })
  @Column({
    type: 'varchar',
    length: 20,
    default: RecommendationStatus.Recommended,
  })
  status: RecommendationStatus;

  @ApiProperty({
    enum: RecommendationPriority,
    description: 'Urgency level inferred from client diagnostics',
    default: RecommendationPriority.Medium,
  })
  @Column({
    type: 'varchar',
    length: 20,
    default: RecommendationPriority.Medium,
  })
  priority: RecommendationPriority;

  @ApiPropertyOptional({
    description: 'Short AI/diagnostic rationale shown to the client',
  })
  @Column({ type: 'text', nullable: true })
  rationale: string | null;

  @ApiProperty({
    description: 'Recommendation prerequisite IDs from the dependency graph',
    type: [String],
  })
  @Column({ type: 'jsonb', default: () => "'[]'" })
  dependencyIds: string[];

  @ApiProperty({
    description: 'Signals matched during recommendation generation',
    type: [String],
  })
  @Column({ type: 'jsonb', default: () => "'[]'" })
  diagnosticSignals: string[];

  @ApiPropertyOptional({
    description: 'When recommendation was generated by the matching service',
  })
  @Column({ type: 'timestamptz', nullable: true })
  generatedAt: Date | null;

  @ApiProperty({ description: 'Recommendation creation date' })
  @CreateDateColumn()
  createdAt: Date;

  @ApiProperty({ description: 'Recommendation update date' })
  @UpdateDateColumn()
  updatedAt: Date;
}
