import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';
import { User } from '../../users/entities/user.entity';
import { ChatSession } from './chat-session.entity';

@Entity()
export class ChatMessage {
  @ApiProperty({ description: 'Message ID (UUID)' })
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ApiProperty({ description: 'Session ID' })
  @Index()
  @Column({ type: 'uuid' })
  sessionId: string;

  @ManyToOne(() => ChatSession, (session) => session.messages, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'sessionId' })
  session: ChatSession;

  @ApiProperty({ description: 'Sender user ID' })
  @Column({ type: 'uuid' })
  senderId: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'senderId' })
  sender: User;

  @ApiProperty({ description: 'Message text' })
  @Column({ type: 'text' })
  text: string;

  @ApiProperty({ description: 'Whether the message has been read' })
  @Column({ type: 'boolean', default: false })
  isRead: boolean;

  @ApiProperty({
    description:
      'True when the message was generated by the AI system user (the ' +
      '"AI-консультант AltaSales" virtual account). Used by the frontend to ' +
      'render the AI badge and by the RAG history mapper to tag the message ' +
      'as an assistant turn.',
  })
  @Column({ type: 'boolean', default: false })
  isAiGenerated: boolean;

  @ApiProperty({ description: 'Message creation date' })
  @CreateDateColumn()
  createdAt: Date;
}
